import LegalPage from "./LegalPage";

export default function Terms() {
  return (
    <LegalPage eyebrow="Creative Adhyayan" title="Privacy Policy & Student Terms and Conditions" updated="September 29, 2026">
      <p>At Creative Adhyayan, we are committed to providing quality education and a positive learning environment for all our students. Please read the following policies carefully before taking admission.</p>
      <section><h2>1. No Refund Policy</h2><p>All admissions at Creative Adhyayan are considered final. Once a student has completed the admission process, the admission fee and course fee are non-refundable. No refund of the admission amount or any fee paid will be provided after admission, regardless of the reason for cancellation, withdrawal, or discontinuation of the course.</p></section>
      <section><h2>2. Admission Fee Policy</h2><p>The admission fee paid at the time of enrollment is non-refundable. Students are advised to carefully review the course details, duration, fee structure, and other terms before confirming their admission.</p></section>
      <section><h2>3. Course Fee Policy</h2><p>Once admission is confirmed, the course fee paid by the student is non-refundable. Students who choose to discontinue the course, stop attending classes, or withdraw for personal reasons will not be eligible for a refund of the fees paid.</p></section>
      <section><h2>4. Class Attendance Policy</h2><p>Students are expected to attend classes regularly and maintain consistent participation throughout the course. It is the student's responsibility to attend scheduled classes and complete the course activities.</p></section>
      <section><h2>5. Missed Classes and Re-Teaching Policy</h2><p>If a student misses a scheduled class for any reason, Creative Adhyayan does not guarantee that the missed class will be retaught individually or repeated separately. Students are responsible for managing their attendance and keeping up with the course curriculum.</p><p>Any additional support, revision sessions, or access to missed class materials will be provided at the institute's discretion, subject to availability.</p></section>
      <section><h2>6. Placement Assistance Policy</h2><p>Creative Adhyayan provides placement assistance to eligible students to help them explore employment opportunities after completing their course.</p><p>Placement assistance may include career guidance, interview preparation, resume-building support, and information about relevant job opportunities.</p><p>Placement assistance does not mean a guaranteed job or placement. Creative Adhyayan does not guarantee employment, a specific salary, or placement with any particular company. Final hiring decisions depend on the student's skills, performance, qualifications, and the employer's requirements.</p><p>Students are responsible for their own career development and job application process.</p></section>
      <section><h2>7. Student Acknowledgment</h2><p>By enrolling in any course at Creative Adhyayan, students acknowledge that they have read, understood, and agreed to the admission, fee, refund, attendance, and placement policies mentioned above.</p><p>Students are encouraged to clarify any questions regarding the course, fees, attendance requirements, or placement assistance before completing their admission.</p></section>
      <section><h2>18. Governing Law and Jurisdiction</h2><p>These Terms &amp; Conditions shall be governed by and interpreted in accordance with the laws applicable in India.</p><p>Any disputes, claims, or legal proceedings arising out of or in connection with these Terms &amp; Conditions, admission, fees, or services provided by Creative Adhyayan shall be subject to the exclusive jurisdiction of the competent courts in Delhi, India, subject to applicable law.</p></section>
      <p className="font-semibold">Creative Adhyayan — Learn Skills. Build Your Future.</p>
    </LegalPage>
  );
}
